key_webserver_name: "webserver_key"
key_dbserver_name: "dbserver_key"
key_sshserver_name: "sshserver_key"
ec2_webserver_name: "WebServer-EC2"
ec2_dbserver_name: "DataBase-EC2"
ec2_sshserver_name: "SSHServer-EC2"
ami_id: "ami-050cd642fd83388e4"
ami_web_id: "ami-0232267303ef39abf"
ami_db_id: "ami-04ac74f94359e134b"
iam_role_name: "EC2Role"
secret_name: "secret_test"
region: "us-east-2"
kms_key_id: "arn:aws:kms:us-east-2:537124946613:key/c620773f-1589-4a65-a45a-a362a0e6334b"
volume_size: 10
instance_type: "t2.micro"
encrypted: true