region: "us-east-2"
vpc_cidr: "10.0.0.0/16"
vpc_name: "WebApplication-VPC"
subnet_cidr: "10.0.1.0/24"
subnet_db_cidr: "10.0.2.0/24"
subnet_ssh_cidr: "10.0.3.0/24"
subnet_name: "WebServer-Subnet"
igw_name: "WebApplication-IGW"
security_group_name: "WebServer-SG"
subnet_db_name: "DataBase-Subnet"
security_group_name_db: "DataBase-SG"
subnet_ssh_name: "SSH-Subnet"
security_group_name_ssh: "SSH-SG"
route_table_name_outside: "Outside-RouteTable"
route_table_name_inside: "Inside-RouteTable"