# create_network.yml

- name: Create AWS Network Infrastructure
  hosts: localhost
  vars:
    subnet_cidr: "10.0.1.0/24"
    region: "us-east-2"
    vpc_id: "vpc-0a99c7319c2e931cb"
    subnet_name: "WebServer-Subnet"
    igw_name: "WebApplication-IGW"
    route_table_name: "WebServer-RouteTable"
    security_group_name: "WebServer-SG"
    
  tasks:
    - name: Create Subnet
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc_id }}"
        cidr: "{{ subnet_cidr }}"
        region: "{{ region }}"
        az: "{{ region }}a"
        tags:
          Name: "{{ subnet_name }}"
      register: subnet

    - name: Create Internet Gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        tags:
          Name: "{{ igw_name }}"
      register: igw

    - name: Create Route Table
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        tags:
          Name: "{{ route_table_name }}"
        subnets:
          - "{{ subnet.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw.gateway_id }}"
      register: route_table

    - name: Create Security Group
      amazon.aws.ec2_security_group:
        name: "{{ security_group_name }}"
        description: "Security Group for Web Server"
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        tags:
          Name: "{{ security_group_name }}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: "0.0.0.0/0"
            group_desc: "Allow HTTP"
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "0.0.0.0/0"
            group_desc: "Allow SSH"
      register: security_group