# create_network.yml

- name: Create AWS Network Infrastructure
  hosts: localhost
  vars:
    subnet_cidr: "10.0.1.0/24"
    region: "us-east-2"
    vpc_id: "vpc-05f34ccb9433dee73"
    subnet_name: "WebServer-Subnet"
    igw_name: "WebApplication-IGW"
    route_table_name: "WebServer-RouteTable"
    security_group_name: "WebServer-SG"
    subnet_db_cidr: "10.0.2.0/24"
    subnet_db_name_db: "DataBase-Subnet"
    route_table_name_db: "DataBase-RouteTable"
    security_group_name_db: "DataBase-SG"
    key_webserver_name: "webserver_key"
    key_dbserver_name: "dbserver_key"
    ec2_webserver_name: "WebServer-EC2"
    ec2_dbserver_name: "DataBase-EC2"
    ami_id: "ami-050cd642fd83388e4"
    
  tasks:
    - name: Create Subnet
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc_id }}"
        cidr: "{{ subnet_cidr }}"
        region: "{{ region }}"
        az: "{{ region }}a"
        tags:
          Name: "{{ subnet_name }}"
      register: subnet

    - name: Create Internet Gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        tags:
          Name: "{{ igw_name }}"
      register: igw

    - name: Create Route Table
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        tags:
          Name: "{{ route_table_name }}"
        subnets:
          - "{{ subnet.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw.gateway_id }}"
      register: route_table

    - name: Create Security Group
      amazon.aws.ec2_security_group:
        name: "{{ security_group_name }}"
        description: "Security Group for Web Server"
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        tags:
          Name: "{{ security_group_name }}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: "0.0.0.0/0"
            group_desc: "Allow HTTP"
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "0.0.0.0/0"
            group_desc: "Allow SSH"
      register: security_group

    - name: Create subnet DB
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc_id }}"
        cidr: "{{ subnet_db_cidr }}"
        region: "{{ region }}"
        az: "{{ region }}a"
        tags:
          Name: "{{ subnet_db_name_db }}"
      register: subnet_db

    - name: Create Route Table DB
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        tags:
          Name: "{{ route_table_name_db }}"
        subnets:
          - "{{ subnet_db.subnet.id }}"
          - "{{ subnet.subnet.id }}"
      register: route_table_db

    - name: Create Security Group DB
      amazon.aws.ec2_security_group:
        name: "{{ security_group_name_db }}"
        description: "Security Group for DataBase Server"
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        tags:
          Name: "{{ security_group_name_db }}"
        rules:
          - proto: tcp
            from_port: 3306
            to_port: 3306
            cidr_ip: "0.0.0.0/0"
            group_desc: "Allow MySQL"
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "0.0.0.0/0"
            group_desc: "Allow SSH"
      register: security_group_db
    
    - name: Create WebServer Instance
      amazon.aws.ec2_instance:
        name: "{{ ec2_webserver_name }}"
        key_name: "{{ key_webserver_name }}"
        vpc_subnet_id: "{{ subnet.subnet.id }}"
        instance_type: t2.micro
        image_id: "{{ ami_id }}"
        security_group: "{{ security_group.group_name }}"
        network_interfaces:
          - assign_public_ip: true

    - name: Create DBServer Instance
      amazon.aws.ec2_instance:
        name: "{{ ec2_dbserver_name }}"
        key_name: "{{ key_dbserver_name }}"
        vpc_subnet_id: "{{ subnet_db.subnet.id }}"
        instance_type: t2.micro
        image_id: "{{ ami_id }}"
        security_group: "{{ security_group_db.group_name }}"

  