# launch_instance.yml

- name: Create AWS Network Infrastructure
  hosts: localhost
  vars:
    user_data_dir: "../user-data"
    configs_dir: "../configs"
  tasks:
    - name: Load initial instances variables
      include_vars:
        file: "{{ configs_dir }}/instances.yml"
  
    - name: Load network configuration variables
      include_vars:
        file: "{{ configs_dir }}/network_config.yml"
  
    - name: Create WebServer Instance
      amazon.aws.ec2_instance:
        name: "{{ ec2_webserver_name }}"
        key_name: "{{ key_webserver_name }}"
        vpc_subnet_id: "{{ subnet_id }}"
        instance_type: t2.micro
        image_id: "{{ ami_id }}"
        security_group: "{{ security_group_name }}"
        user_data: "{{ lookup('file', user_data_dir + 'user-data-webserver.sh') }}"
        network_interfaces:
          - assign_public_ip: true
      register: ec2_webserver
      
    - name: Create DBServer Instance
      amazon.aws.ec2_instance:
        name: "{{ ec2_dbserver_name }}"
        key_name: "{{ key_dbserver_name }}"
        vpc_subnet_id: "{{ subnet_db_id }}"
        instance_type: t2.micro
        image_id: "{{ ami_id }}"
        security_group: "{{ security_group_db_name }}"
        user_data: "{{ lookup('file', user_data_dir + 'user-data-dbserver.sh') }}"
      register: ec2_dbserver

    - name: Create SSH Server Instance
      amazon.aws.ec2_instance:
        name: "{{ ec2_sshserver_name }}"
        key_name: "{{ key_sshserver_name }}"
        vpc_subnet_id: "{{ subnet_shh_id }}"
        instance_type: t2.micro
        image_id: "{{ ami_id }}"
        security_group: "{{ security_group_ssh_name }}"
        user_data: "{{ lookup('file', user_data_dir + 'user-data-shserver.sh') }}"
        network_interfaces:
          - assign_public_ip: true
      register: ec2_sshserver

    - name: Save Instances Configuration to File
      copy:
        dest: instances_config.yml
        content: |
          ec2_webserver_ids: "{{ ec2_webserver.instances[0].instance_id }}"
          ec2_dbserver_ids: "{{ ec2_dbserver.instances[0].instance_id }}"
          ec2_sshserver_ids: "{{ ec2_sshserver.instances[0].instance_id }}"