# main.yml
- name: Orchestrate AWS Infrastructure Deployment
  hosts: localhost
  gather_facts: no
  vars:
    user_data_dir: "../user-data"
    configs_dir: "../configs"
  tasks:
    - name: Create Network Infrastructure
      include_tasks: create_network.yml
      register: network_result

    - name: Launch Instances
      include_tasks: launch_instance.yml
      register: instance_result

    - name: Run Rollback if any task failed
      include_tasks: rollback.yml
      when: network_result is failed or instance_result is failed
      tags: rollback