# rollback.yml
- name: Rollback AWS Infrastructure
  hosts: localhost
  gather_facts: no
  vars:
    configs_dir: "../configs"

  tasks:
    - name: Load network configuration variables
      ansible.builtin.include_vars:
        file: "{{ configs_dir }}/network_config.yml"
      tags: RemoveVPC

    - name: Load Instances configuration variables
      ansible.builtin.include_vars:
        file: "{{ configs_dir }}/instances_config.yml"

    - name: Terminate WebServer Instance
      amazon.aws.ec2_instance:
        state: absent
        wait: true
        instance_ids:
          - "{{ ec2_webserver_ids }}"
      register: webserver_terminated

    - name: Terminate DBServer Instance
      amazon.aws.ec2_instance:
        state: absent
        wait: true
        instance_ids:
          - "{{ ec2_dbserver_ids }}"
      register: dbserver_terminated

    - name: Terminate SSH Server Instance
      amazon.aws.ec2_instance:
        state: absent
        wait: true
        instance_ids:
          - "{{ ec2_sshserver_ids }}"
      register: sshserver_terminated

    - name: Wait for Instances to Terminate Completely
      amazon.aws.ec2_instance_info:
        instance_ids:
          - "{{ ec2_webserver_ids }}"
          - "{{ ec2_dbserver_ids }}"
          - "{{ ec2_sshserver_ids }}"
      register: instances_check
      retries: 10
      delay: 30

    - name: Remove Subnet Web Server
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc_id }}"
        cidr: "10.0.1.0/24"
        state: absent
      tags: RemoveVPC

    - name: Remove Subnet DB Server
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc_id }}"
        cidr: "10.0.2.0/24"
        state: absent
      tags: RemoveVPC

    - name: Remove Subnet DB Server
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc_id }}"
        cidr: "10.0.3.0/24"
        state: absent
      tags: RemoveVPC

    - name: Detach and Delete Internet Gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc_id }}"
        state: absent
      tags: RemoveVPC

    - name: delete route table outside
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc_id }}"
        route_table_id: "{{ route_table_outside_id }}"
        lookup: id
        state: absent
      tags: RemoveVPC

    - name: delete route table inside
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc_id }}"
        route_table_id: "{{ route_table_name_inside_id }}"
        lookup: id
        state: absent
      tags: RemoveVPC

    - name: delete Security group Web Server
      amazon.aws.ec2_security_group:
        group_id: "{{ security_group_id }}"
        state: absent
      tags: RemoveVPC

    - name: delete Security group DB Server
      amazon.aws.ec2_security_group:
        group_id: "{{ security_group_db_id }}"
        state: absent
      tags: RemoveVPC

    - name: delete Security group SSH Server
      amazon.aws.ec2_security_group:
        group_id: "{{ security_group_ssh_id }}"
        state: absent
      tags: RemoveVPC

    - name: Remove VPC if no instances remain (conditional rollback)
      amazon.aws.ec2_vpc_net:
        vpc_id: "{{ vpc_id }}"
        state: absent
        purge_cidrs: yes
      tags: RemoveVPC
