# rollback.yml
- name: Rollback AWS Infrastructure
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Load network configuration variables
      include_vars:
        file: network_config.yml
  
    - name: Load Instances configuration variables
      include_vars:
        file: instances_config.yml

    - name: Terminate WebServer Instance
      amazon.aws.ec2_instance:
        state: absent  
        wait: yes
        instance_ids:
          - "{{ ec2_webserver_ids }}"
      register: webserver_terminated

    - name: Terminate DBServer Instance
      amazon.aws.ec2_instance:
        state: absent  
        wait: yes
        instance_ids:
          - "{{ ec2_dbserver_ids }}"
      register: dbserver_terminated

    - name: Terminate SSH Server Instance
      amazon.aws.ec2_instance:
        state: absent 
        wait: yes
        instance_ids:
          - "{{ ec2_sshserver_ids }}"
      register: dbserver_terminated

    - name: Remove VPC if no instances remain (conditional rollback)
      amazon.aws.ec2_vpc_net:
        vpc_id: "{{ vpc_id }}"
        state: absent
      when: webserver_terminated.changed and dbserver_terminated.changed