# main.yml
- name: Orchestrate AWS Infrastructure Deployment
  hosts: localhost
  gather_facts: no
  vars:
    user_data_dir: "../user-data"
    configs_dir: "../configs"
  tasks:
    - name: Load network configuration variables
      include_vars:
        file: "{{ configs_dir }}/network_config.yml"

    - name: Load initial networks variables
      include_vars:
        file: "{{ configs_dir }}/networks.yml"

    - name: Create Route Table OutSide
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        tags:
          Name: "{{ route_table_name_outside }}"
        subnets:
          - "{{ subnet_web_id }}"
          - "{{ subnet_shh_id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw.gateway_id }}"
      register: route_table_outside